SRC = ./src/code.c ./src/create_file.c ./src/dsm.c ./src/init.c ./src/op.c ./src/parse.c
INCLUDES = ./includes/dsm.h ./includes/op.h
FLAGS =  -Wall -Werror -Wextra

all: $(NAME)

re: fclean all

$(NAME):
	gcc $(SRC) $(INCLUDES) $(FLAGS)

cleam:

fclean:

all: